const COUNTRY_NAMES_PT: Record<string, string> = {
  ABW: "Aruba",
  AFG: "Afeganistão",
  AGO: "Angola",
  AIA: "Anguilla",
  ALB: "Albânia",
  AND: "Andorra",
  ARE: "Emirados Árabes Unidos",
  ARG: "Argentina",
  ARM: "Armênia",
  ASM: "Samoa Americana",
  ATF: "Territórios Franceses do Sul",
  ATG: "Antígua e Barbuda",
  AUS: "Austrália",
  AUT: "Áustria",
  AZE: "Azerbaijão",
  BDI: "Burundi",
  BEL: "Bélgica",
  BEN: "Benin",
  BES: "Bonaire, Sint Eustatius e Saba",
  BFA: "Burkina Faso",
  BGD: "Bangladesh",
  BGR: "Bulgária",
  BHR: "Bahrein",
  BHS: "Bahamas",
  BIH: "Bósnia e Herzegovina",
  BLM: "São Bartolomeu",
  BLR: "Bielorrússia",
  BLZ: "Belize",
  BMU: "Bermudas",
  BRB: "Barbados",
  BRN: "Brunei",
  BRA: "Brasil",
  BTN: "Butão",
  BWA: "Botswana",
  CAF: "República Centro-Africana",
  CAN: "Canadá",
  CCK: "Ilhas Cocos",
  CHE: "Suíça",
  CHL: "Chile",
  CHN: "China",
  CIV: "Costa do Marfim",
  CMR: "Camarões",
  COD: "República Democrática do Congo",
  COG: "Congo",
  COK: "Ilhas Cook",
  COL: "Colômbia",
  COM: "Comores",
  CPV: "Cabo Verde",
  CRI: "Costa Rica",
  CUB: "Cuba",
  CUW: "Curaçao",
  CXR: "Ilha Christmas",
  CYM: "Ilhas Cayman",
  CYP: "Chipre",
  CZE: "República Tcheca",
  DEU: "Alemanha",
  DJI: "Djibuti",
  DMA: "Dominica",
  DNK: "Dinamarca",
  DOM: "República Dominicana",
  DZA: "Argélia",
  ECU: "Equador",
  EGY: "Egito",
  ERI: "Eritreia",
  ESP: "Espanha",
  EST: "Estônia",
  ETH: "Etiópia",
  FIN: "Finlândia",
  FJI: "Fiji",
  FLK: "Ilhas Malvinas",
  FRA: "França",
  FSM: "Micronésia",
  GAB: "Gabão",
  GBR: "Reino Unido",
  GEO: "Geórgia",
  GHA: "Gana",
  GIB: "Gibraltar",
  GIN: "Guiné",
  GNB: "Guiné-Bissau",
  GNQ: "Guiné Equatorial",
  GRC: "Grécia",
  GRD: "Granada",
  GRL: "Groenlândia",
  GTM: "Guatemala",
  GUM: "Guam",
  GUY: "Guiana",
  HKG: "Hong Kong",
  HND: "Honduras",
  HRV: "Croácia",
  HTI: "Haiti",
  HUN: "Hungria",
  IDN: "Indonésia",
  IND: "Índia",
  IOT: "Território Britânico do Oceano Índico",
  IRL: "Irlanda",
  IRN: "Irã",
  IRQ: "Iraque",
  ISL: "Islândia",
  ISR: "Israel",
  ITA: "Itália",
  JAM: "Jamaica",
  JOR: "Jordânia",
  JPN: "Japão",
  KAZ: "Cazaquistão",
  KEN: "Quênia",
  KGZ: "Quirguistão",
  KHM: "Camboja",
  KIR: "Kiribati",
  KNA: "São Cristóvão e Nevis",
  KOR: "Coreia do Sul",
  KWT: "Kuwait",
  LAO: "Laos",
  LBN: "Líbano",
  LBR: "Libéria",
  LBY: "Líbia",
  LCA: "Santa Lúcia",
  LSO: "Lesoto",
  LTU: "Lituânia",
  LUX: "Luxemburgo",
  LVA: "Letônia",
  MAC: "Macau",
  MAR: "Marrocos",
  MDA: "Moldávia",
  MDG: "Madagáscar",
  MDV: "Maldivas",
  MEX: "México",
  MHL: "Ilhas Marshall",
  MKD: "Macedônia do Norte",
  MLI: "Mali",
  MLT: "Malta",
  MMR: "Mianmar",
  MNE: "Montenegro",
  MNG: "Mongólia",
  MNP: "Ilhas Marianas do Norte",
  MOZ: "Moçambique",
  MRT: "Mauritânia",
  MSR: "Montserrat",
  MUS: "Maurício",
  MWI: "Malawi",
  MYS: "Malásia",
  NAM: "Namíbia",
  NCL: "Nova Caledônia",
  NER: "Níger",
  NFK: "Ilha Norfolk",
  NGA: "Nigéria",
  NIC: "Nicarágua",
  NIU: "Niue",
  NLD: "Países Baixos",
  NOR: "Noruega",
  NPL: "Nepal",
  NRU: "Nauru",
  NZL: "Nova Zelândia",
  OMN: "Omã",
  PAK: "Paquistão",
  PAN: "Panamá",
  PCN: "Pitcairn",
  PER: "Peru",
  PHL: "Filipinas",
  PLW: "Palau",
  PNG: "Papua-Nova Guiné",
  POL: "Polônia",
  PRT: "Portugal",
  PRK: "Coreia do Norte",
  PRY: "Paraguai",
  PSE: "Palestina",
  PYF: "Polinésia Francesa",
  QAT: "Catar",
  ROU: "Romênia",
  RUS: "Rússia",
  RWA: "Ruanda",
  S19: "Taiwan",
  SAU: "Arábia Saudita",
  SDN: "Sudão",
  SEN: "Senegal",
  SGP: "Singapura",
  SHN: "Santa Helena",
  SLB: "Ilhas Salomão",
  SLE: "Serra Leoa",
  SLV: "El Salvador",
  SMR: "San Marino",
  SOM: "Somália",
  SPM: "Saint Pierre e Miquelon",
  SRB: "Sérvia",
  SSD: "Sudão do Sul",
  STP: "São Tomé e Príncipe",
  SUR: "Suriname",
  SVK: "Eslováquia",
  SVN: "Eslovênia",
  SWE: "Suécia",
  SWZ: "Essuatíni",
  SXM: "Sint Maarten",
  SYC: "Seicheles",
  SYR: "Síria",
  TCA: "Ilhas Turks e Caicos",
  TCD: "Chade",
  TGO: "Togo",
  THA: "Tailândia",
  TJK: "Tajiquistão",
  TKL: "Tokelau",
  TKM: "Turcomenistão",
  TLS: "Timor-Leste",
  TON: "Tonga",
  TTO: "Trinidad e Tobago",
  TUN: "Tunísia",
  TUR: "Turquia",
  TUV: "Tuvalu",
  TZA: "Tanzânia",
  UGA: "Uganda",
  UKR: "Ucrânia",
  URY: "Uruguai",
  USA: "Estados Unidos",
  UZB: "Uzbequistão",
  VCT: "São Vicente e Granadinas",
  VEN: "Venezuela",
  VGB: "Ilhas Virgens Britânicas",
  VNM: "Vietnã",
  VUT: "Vanuatu",
  WLF: "Wallis e Futuna",
  WSM: "Samoa",
  YEM: "Iêmen",
  ZAF: "África do Sul",
  ZMB: "Zâmbia",
  ZWE: "Zimbábue",
};

export function getCountryName(iso3: string): string {
  return COUNTRY_NAMES_PT[iso3] ?? iso3;
}
